apiVersion: v2
name: conveyor
appVersion: "0.5.0"
version: 0.5.0
kubeVersion: ">=1.19.0-0"
description: Conveyor CI is an Engine/Framwork for building custom CI/CD Platforms.
home: https://conveyor.open.ug/
icon: https://conveyor.open.ug/img/logo.png
sources:
  - https://github.com/open-ug/conveyor
maintainers:
  - name: jim-junior
    email: jimjunior854@gmail.com
    url: https://github.com/jim-junior
type: application
keywords:
  - cicd
  - devops
  - monitoring