# Edit this file to configure your Docker Compose setup
services:
  app:
    image: openug/conveyor:latest
    container_name: app
    depends_on:
      - etcd
      - loki
      - nats
    ports:
      - "8080:8080"
      - "4222:4222"
    networks:
      - conveyor-network

volumes:
  app-data:

networks:
  conveyor-network:
    driver: bridge
