apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ include "conveyor.fullname" . | default "conveyor" | trim }}-config"
  namespace: "{{ include "conveyor.namespace" . | default "default" | trim }}"

data:
  conveyor.yml: |
    api:
      auth_enabled: false
