apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: "{{ include "conveyor.fullname" . | default "conveyor" | trim }}"
  namespace: "{{ include "conveyor.namespace" . | default "default" | trim }}"
  labels:
    app.kubernetes.io/name: "{{ include "conveyor.fullname" . | default "conveyor" | trim }}-config"
    app.kubernetes.io/instance: {{ .Release.Name }}
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: {{ .Values.pvc.size | default "16Gi" }}
  storageClassName: {{ .Values.storageClass | default "standard" }}

