apiVersion: v1 
kind: PersistentVolumeClaim
metadata: 
  name: {{ include "conveyor.fullname" . }}
  namespace: {{ include "conveyor.namespace" . }}
  labels:
    app.kubernetes.io/name: {{ include "conveyor.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: {{ .Values.pvc.size | default "16Gi" }}
  storageClassName: {{ .Values.storageClass | default "standard" }}

