apiVersion: v1
kind: Service
metadata:
  name: {{ include "conveyor.fullname . " }}  
namespace: {{ include "conveyor.namespace" . }}
  labels: 
    app.kubernetes.io/name: {{ include "conveyor.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: {{ include "conveyor.fullname" . }}
    
  ports:
    - name: api
      port: {{ .Values.service.ports.api | default 8080 }}
      targetPort: 8080
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      {{- end }}
      protocol: TCP

    - name: nats
      port: {{ .Values.service.ports.nats | default 4222 }}
      targetPort: 4222
      protocol: TCP
