apiVersion: v1
kind: Service
metadata:
  name: conveyor
  namespace: { { include "conveyor.namespace" . } }
spec:
  selector:
    app: conveyor
  ports:
    - port: { { .Values.api.service.servicePort | default 8080 } }
      targetPort: 8080
      nodePort: 30080
  type: NodePort
