apiVersion: v1
kind: Service
metadata:
  name: "{{ include "conveyor.fullname" . | default "conveyor" | trim }}-config"
  namespace: "{{ include "conveyor.namespace" . | default "default" | trim }}"
  labels: 
    app.kubernetes.io/name: "{{ include "conveyor.fullname" . | default "conveyor" | trim }}-config"
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    app.kubernetes.io/managed-by: Helm
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  selector:
    app.kubernetes.io/name: "{{ include "conveyor.fullname" . | default "conveyor" | trim }}-config"
    
  ports:
    - name: api
      port: {{ .Values.service.ports.api | default 8080 }}
      targetPort: 8080
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort | default 30080 }}
      {{- end }}
      protocol: TCP

    - name: nats
      port: {{ .Values.service.ports.nats | default 4222 }}
      targetPort: 4222
      protocol: TCP
